---
# tasks file for scale-up-orderers
  - name: Get a list of all deployments from any namespace
    k8s_info:
      kind: Deployment
    register: deployment_list

  - name: Set orderer_names from the deployment_list
    set_fact:
      orderer_names: "{{ deployment_list | to_json | from_json | json_query('resources[*].metadata|[?contains(name,`orderer`)].name') }}"

  - name: Print deployment names
    debug:
      msg: "{{ deployment_list | to_json | from_json | json_query('resources[*].metadata|[?contains(name,`orderer`)].name') }}"

  - name: Scale up the orderers deployment's to 1
    k8s_scale:
      api_version: v1
      kind: Deployment
      name: "{{ item  }}"
      namespace: default
      replicas: 1
      wait_timeout: 60
    loop: "{{ orderer_names|flatten(levels=1) }}"