- name: Get the pod name of peer_cli in the given namespace
  k8s_facts:
    api_version: v1
    kind: pod
    namespace: {{ namespace }}
    label_selectors:
      - app = cli
  register: peer_cli_podname

- name: Checkout fabric samples in to GOPATH
  git:
    repo: https://github.com/hyperledger/fabric-samples.git
    dest: /go/src/

- name: Peer lifecycle chaincode package
  community.kubernetes.k8s_exec:
    namespace: {{ namespace }}
    pod: {{ peer_cli_podname }}
    command: peer lifecycle chaincode package {{ package_name }}.tar.gz  --path github.com/fabric-samples/chaincode/{{ package_name }}/go --lang golang --label {{ label_name }}

- name: Peer lifecycle chaincode install 
  community.kubernetes.k8s_exec:
    namespace: {{ namespace }}
    pod: {{ peer_cli_podname }}
    command: peer lifecycle chaincode install {{ package_name }}.tar.gz

