grafana:
  enabled: true
  grafana.ini:
    smtp:
       enabled: true
       #host: smtp.gmail.com:587
       host: "{{ smtp_endpoint }}"
       user: "{{ smtp_email }}"
       password: "{{ smtp_email_password }} "
       skip_verify: true

prometheus:
  enabled: true
  prometheusSpec:
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: "{{ storageclass_name }}"
          resources:
            requests:
              storage: "{{ prom_operator_storagesize }}"
