grafana:
  enabled: true
  grafana.ini:
    smtp:
       enabled: true
       #host: smtp.gmail.com:587
       host: "{{ monitoring.smtp_endpoint }}"
       user: "{{ monitoring.smtp_email }}"
       password: "{{ monitoring.smtp_email_password }} "
       skip_verify: true

prometheus:
  enabled: true
  prometheusSpec:
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: "{{ monitoring.storageclass_name }}"
          resources:
            requests:
              storage: "{{ monitoring.storagesize }}"
