
# From repository
- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy latest version of Loki chart inside monitoring namespace
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      version: "v1.1.0"
      set: "installCRDs=true"
