{
 "title": "Critical Resources View",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host's Root Volume Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) by (instance) -\r\nsum(node_filesystem_free_bytes{device!=\"rootfs\"}) by (instance)) / \r\nsum(node_filesystem_size_bytes{device!=\"rootfs\"})  by (instance) * 100 > 75"
    }
   ]
  },
  {
   "title": "Host's CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance!~\"(instance)\",mode=\"system\"}[5m])) by (instance) *100 > 70"
    }
   ]
  },
  {
   "title": "Pod  Volume Usage Above 50%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!~\"(volume)\"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim!~\"(volume)\"}) / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!~\"(volume)\"} * 100 > 50",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod  Volume Usage Above 75%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!~\"(volume)\"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim!~\"(volume)\"}) / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!~\"(volume)\"} * 100 > 75",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod Restart Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate (kube_pod_container_status_restarts_total{namespace!~\"(namespace)\",pod!~\"(pod)\",container!~\"(container)\"}[1m])",
     "legendFormat": "{{pod}} "
    }
   ]
  }
 ]
}